### ISSUE TITLE
Make the ChatOps sample code available in the module titled DNA Explained

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/devnet-express-code-samples#13]
An SE is preparing for a DNA event in Pittsburgh. The SE couldn't find the ChatOps bot that we refer to in the demo portion of the DNA Explained module. 

We need to make the ChatOps bot available to the SEs hosting events, and explain to then how to access it.

**Comment by armartirosyan** [comment]
VIRL demo bot has been moved to top level folder and it is ready to be merged with master branch

**Comment by austinMarcos** [comment]
The ChatOps bot is distributed in the code samples repo.
